name: Remove Ephemeral Runner
description: |
  Deregister self hosted runner, remove associated cloud VM on
  Arbutus, and remove runner registration from Github.
inputs:
  pr_number:
    description: "PR number to test"
    required: true
  repository:
    description: "Github repository (owner/name)"
    required: true
  repository_name:
    description: "GitHub repository name"
    required: true
  vm_id:
    description: "The OpenStack VM ID"
    required: true

runs:
  using: composite
  steps:
    - name: Export OpenStack credentials
      shell: bash
      run: |
        echo "OS_AUTH_TYPE=$OS_AUTH_TYPE" >> $GITHUB_ENV
        echo "OS_AUTH_URL=$OS_AUTH_URL" >> $GITHUB_ENV
        echo "OS_USERNAME=$OS_USERNAME" >> $GITHUB_ENV
        echo "OS_USER_DOMAIN_NAME=$OS_USER_DOMAIN_NAME" >> $GITHUB_ENV
        echo "OS_APPLICATION_CREDENTIAL_ID=$OS_APPLICATION_CREDENTIAL_ID" >> $GITHUB_ENV
        echo "OS_APPLICATION_CREDENTIAL_SECRET=$OS_APPLICATION_CREDENTIAL_SECRET" >> $GITHUB_ENV
        echo "RUNNER_PAT=$RUNNER_PAT" >> $GITHUB_ENV

    - name: Install Openstack CLI & tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-openstackclient jq gettext-base

    - name: Deregister runner
      shell: bash
      env:
        VM_ID: ${{ inputs.vm_id }}
      run: |
        # get removal token
        token=$(curl -sX POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${RUNNER_PAT}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.repository }}/actions/runners/remove-token \
          | jq -r .token)

        # fetch IP address of the VM
        ip=$(openstack server show "$VM_ID" -f value -c addresses | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)

        echo "Resolved IP for VM $VM_ID: $ip"

        # check console log for runner removal
        openstack console log show "$VM_ID" | grep -q 'Runner listener launched' && \
          openstack console log show "$VM_ID" | grep -q 'Runner removed'

        # delete VM
        openstack server delete "$VM_ID" || true

    - name: Delete VM fallback
      shell: bash
      run: |
        openstack server delete ${{ inputs.vm_id }} || true

    - name: Remove runner registration from GitHub
      shell: bash
      run: |
        runner_id=$(curl -sS \
          -H "Authorization: token $RUNNER_PAT" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ inputs.repository }}/actions/runners \
          | jq -r --arg NAME "${{ github.event.repository.name }}-pr-${{ inputs.pr_number }}" \
              '.runners[] | select(.name==$NAME) | .id')

        if [ -n "$runner_id" ]; then
          echo "Deleting runner ID $runner_id from ${{ inputs.repository }} …"
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.repository }}/actions/runners/$runner_id
        else
          echo "No runner '${{ github.event.repository.name }}-pr-${{ inputs.pr_number }}' found in ${{ inputs.repository }}"
        fi
