name: Setup Snakebids Environment
description: |
  Sets up Miniforge with Mamba and installs Snakebids.
runs:
  using: "composite"
  steps:
    - name: Setup Miniforge and mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        mamba-version: "*"
        use-mamba: true
        conda-solver: libmamba
        auto-activate-base: true

    - name: Install snakebids with mamba
      shell: bash -l {0}
      run: |
        mamba install -y python=3.11 -c bioconda -c conda-forge snakebids