---
name: Deploy Docker container
on:
  workflow_call:
    inputs:
      maximize_space:
        description: Maximize available space for building container
        required: false
        default: false
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Maximize space available for buiilding docker container
        if: inputs.maximize_space
        uses: easimon/maximize-build-space@v10
        with:
          remove-android: "true" # android sdk
          remove-codeql: "true" # code scanning
          remove-dotnet: "true" # .net sdk
          remove-haskell: "true" # haskell
          remove-docker-images: "true" # rm cached images
          overprovision-lvm: "true" # "overuse" disk space

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GH container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker container
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto

      - name: Build and push Docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
